name: Build and Run Docker Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t my-python-app .

    - name: Run Docker container
      run: |
        docker run -d --name my-running-app -p 80:80 -p 8000:8000 my-python-app

    - name: List running Docker containers
      run: |
        docker ps

    - name: Show logs from Docker container
      run: |
        docker logs my-running-app

    - name: Stop and remove Docker container
      if: always()
      run: |
        docker stop my-running-app
        docker rm my-running-app

    - name: Push changes to GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/team_222/mlops_pr.git
        git fetch gitlab
        git push -u gitlab main

