name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      api:
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.10
        ports:
          - 8000:8000
        options: >-
          --health-cmd="curl --fail http://127.0.0.1:8000/ || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest httpx gdown Pillow ultralytics
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Start FastAPI server
      run: |
        uvicorn st_app:app --host 0.0.0.0 --port 8000 &
        # Wait for the server to start
        sleep 10
    - name: Test with pytest
      run: pytest

    - name: Print Docker logs
      run: docker logs ${{ job.services.api.id }}
